### ISSUE TITLE
Implement LM-Eval for language model evals

### ISSUE THREAD

**Issue by Rohan138** [mukobi/Unadaptable-Foundation-Models#7] opened 2024-03-30 18:15 UTC
Use [`lm_eval`](https://github.com/EleutherAI/lm-evaluation-harness) to run evals. Replace current code in `utils.py::test`.

**Comment by mukobi** [comment] 2024-04-17 15:37
Dupe of #10

**Closed by mukobi** 2024-04-17 15:37 UTC
